version: '3.3'
services:
  ria-golang:
    environment:
    -   APP_PORT=:8080
    -  MONGO_USERNAME=root
    -  MONGO_PASSWORD=example
    -  MONGO_URL=mongodb://root:example@ria-mongo:27017/?maxPoolSize=70
    -  JWT_SECRET=295fd7a34cae2ccbb52d874ad43066e50460d8029f361f590ae5a30e2724362b67c670cabd04901edd35d880f3d0147c2abf1ffa31a4e54836ce46e6024d76eac4cca8711a0b827cd4eaa105dda89c275cde79609f8bcf4ba3b7b77716f3c1c4c84169b52ed8751637b567d920fc2af4e12246f462756aaf54bef8887d893d896fc3a555adf6a12581f8d59cdae790c4b4b5909e35780e1b086940463e4dd3c103ccf75173e6e9704e59e1f01c07e0a200312cabad17c426a3286758854a8447c2112face7a9dad421ee6f47baa06b6cfcf94a0c21818b93fc45c85db4226c0d3cd1d5f0d7fc7d190bb96e5a4098b6a5ffebcfd61b61792ebdcecff09b83e0ca
